### ISSUE TITLE
Syntax error "(" unexpected in make process

### ISSUE THREAD

**Issue by Nannk** [khadas/u-boot#6]
1. Hello.
I couldnt make u-boot for khadas vim2, due to Syntax error. Make stops on Makefile line 896.
So, it go through 894; then  895, then runs fip_create, and Error. I have no idea what is wrong.

![image](https://user-images.githubusercontent.com/34575742/51246080-8ba4c480-199a-11e9-8f51-ce8de795d57d.png)

**Comment by numbqq** [comment]
Can you paste the log? I can't see what's on the picture...

**Comment by andreyf2** [comment]
okey, here  is it

make

make: Warning: File 'Makefile' has modification time 64407351 s in the future
make[1]: Warning: File '.u-boot.hex.cmd' has modification time 64408130 s in the future
  CHK     include/config/uboot.release
  Using .. as source for U-Boot
  GEN     ./Makefile
  CHK     include/generated/version_autogenerated.h
  CHK     include/generated/timestamp_autogenerated.h
  UPD     include/generated/timestamp_autogenerated.h
  HOSTCC  tools/mkenvimage.o
  HOSTLD  tools/mkenvimage
  HOSTCC  tools/image-host.o
  HOSTCC  tools/dumpimage.o
  HOSTLD  tools/dumpimage
  HOSTCC  tools/mkimage.o
  HOSTLD  tools/mkimage
  AS      arch/arm/cpu/armv8/exceptions.o
  AS      arch/arm/cpu/armv8/cache.o
  AS      arch/arm/cpu/armv8/tlb.o
  AS      arch/arm/cpu/armv8/transition.o
  LD      arch/arm/cpu/armv8/built-in.o
  AS      arch/arm/cpu/armv8/start.o
  CC      common/main.o
  CC      common/board_f.o
  CC      common/cmd_version.o
  LD      common/built-in.o
  CC      drivers/usb/gadget/f_fastboot.o
  LD      drivers/usb/gadget/built-in.o
  CC      lib/display_options.o
  LD      lib/built-in.o
  LD      u-boot
  OBJCOPY u-boot.srec
  OBJCOPY u-boot.bin
  OBJCOPY u-boot.hex
Building board/khadas/kvim2/acs.bin
Building board/khadas/kvim2/bl21.bin
2172+0 records in
2172+0 records out
2172 bytes (2.2 kB, 2.1 KiB) copied, 0.0261651 s, 83.0 kB/s
3936+0 records in
3936+0 records out
3936 bytes (3.9 kB, 3.8 KiB) copied, 0.0466877 s, 84.3 kB/s
cp u-boot.bin ../fip/gxl/bl33.bin
rm -f ../fip/gxl/fip.bin
../fip/fip_create --bl30 ../fip/gxl/bl30_new.bin --bl31 ../fip/gxl/bl31.img --bl33 ../fip/gxl/bl33.bin ../fip/gxl/fip.bin
../fip/fip_create: 1: ../fip/fip_create: Syntax error: "(" unexpected
/home/khadas/Documents/u-boot/Makefile:894: recipe for target 'fip.bin' failed
make[1]: *** [fip.bin] Error 2
Makefile:147: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2

**Comment by Nannk** [comment]
> Can you paste the log? I can't see what's on the picture...
yes, here is it

make

make: Warning: File 'Makefile' has modification time 64407351 s in the future
make[1]: Warning: File '.u-boot.hex.cmd' has modification time 64408130 s in the future
  CHK     include/config/uboot.release
  Using .. as source for U-Boot
  GEN     ./Makefile
  CHK     include/generated/version_autogenerated.h
  CHK     include/generated/timestamp_autogenerated.h
  UPD     include/generated/timestamp_autogenerated.h
  HOSTCC  tools/mkenvimage.o
  HOSTLD  tools/mkenvimage
  HOSTCC  tools/image-host.o
  HOSTCC  tools/dumpimage.o
  HOSTLD  tools/dumpimage
  HOSTCC  tools/mkimage.o
  HOSTLD  tools/mkimage
  AS      arch/arm/cpu/armv8/exceptions.o
  AS      arch/arm/cpu/armv8/cache.o
  AS      arch/arm/cpu/armv8/tlb.o
  AS      arch/arm/cpu/armv8/transition.o
  LD      arch/arm/cpu/armv8/built-in.o
  AS      arch/arm/cpu/armv8/start.o
  CC      common/main.o
  CC      common/board_f.o
  CC      common/cmd_version.o
  LD      common/built-in.o
  CC      drivers/usb/gadget/f_fastboot.o
  LD      drivers/usb/gadget/built-in.o
  CC      lib/display_options.o
  LD      lib/built-in.o
  LD      u-boot
  OBJCOPY u-boot.srec
  OBJCOPY u-boot.bin
  OBJCOPY u-boot.hex
Building board/khadas/kvim2/acs.bin
Building board/khadas/kvim2/bl21.bin
2172+0 records in
2172+0 records out
2172 bytes (2.2 kB, 2.1 KiB) copied, 0.0261651 s, 83.0 kB/s
3936+0 records in
3936+0 records out
3936 bytes (3.9 kB, 3.8 KiB) copied, 0.0466877 s, 84.3 kB/s
cp u-boot.bin ../fip/gxl/bl33.bin
rm -f ../fip/gxl/fip.bin
../fip/fip_create --bl30 ../fip/gxl/bl30_new.bin --bl31 ../fip/gxl/bl31.img --bl33 ../fip/gxl/bl33.bin ../fip/gxl/fip.bin
../fip/fip_create: 1: ../fip/fip_create: Syntax error: "(" unexpected
/home/khadas/Documents/u-boot/Makefile:894: recipe for target 'fip.bin' failed
make[1]: *** [fip.bin] Error 2
Makefile:147: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2

**Comment by numbqq** [comment]
OK. You build u-boot on VIM2... not tested this

It's recommended to cross compile the u-boot on a X86_X64 host.

**Comment by Nannk** [comment]
> OK. You build u-boot on VIM2... not tested this
> 
> It's recommended to cross compile the u-boot on a X86_X64 host.

Thank you.

Upd: Yes, it worked.

**Comment by Nannk** [comment]
And i have one more question. How to install this u-boot.bin? Cause i couldn`t find anything for this particular case.

**Comment by numbqq** [comment]
* Enter u-boot command line
* Load u-boot.bin to DDR from SD card,USB storage or TFTP
* Write u-boot to eMMC.

Example, load u-boot from SD card whit fat32 filesystem:
```
fatload mmc 0 1080000 u-boot.bin
store rom_write 1080000 0 100000
reset
```

**Comment by Nannk** [comment]
Actually, i don't know how to enter u-boot command line. I don't have any
u-boot loading tracers.

It`s only "Khadas" on the screen, then the kernel loads.

**Comment by numbqq** [comment]
OK. May I know why you want to update the u-boot ?

**Comment by Nannk** [comment]
Yes, because i need to mkimage Image(kernel) to uImage, and it displayed
this.            



mkimage –A arm –O linux -T kernel -C none –a 0x30008000 –e 0x30008000 -d /boot/Image  ~/Documents/Image output/uImage
Usage: mkimage -l image
          -l ==> list image header information
       mkimage [-x] -A arch -O os -T type -C comp -a addr -e ep -n name -d data_file[:data_file...] image
          -A ==> set architecture to 'arch'
          -O ==> set operating system to 'os'
          -T ==> set image type to 'type'
          -C ==> set compression type 'comp'
          -a ==> set load address to 'addr' (hex)
          -e ==> set entry point to 'ep' (hex)
          -n ==> set image name to 'name'
          -d ==> use image data from 'datafile'
          -x ==> set XIP (execute in place)
       mkimage [-D dtc_options] [-f fit-image.its|-F] fit-image
          -D => set all options for device tree compiler
          -f => input filename for FIT source
Signing / verified boot not supported (CONFIG_FIT_SIGNATURE undefined)
       mkimage -V ==> print version information and exit
Use -T to see a list of available image types

        so I tried to add  this to config          


CONFIG_ENABLE_VBOOT=y
CONFIG_RSA=y
CONFIG_FIT=y
CONFIG_FIT_SIGNATURE=y
CONFIG_OF_CONTROL=y
CONFIG_OF_SEPARATE=y
CONFIG_OF_LIBFDT=y          


         and make u-boot with it.

**Comment by numbqq** [comment]
You need to setup the serial debug tool in order to enter uboot command line

https://docs.khadas.com/vim1/SetupSerialTool.html

**Comment by Nannk** [comment]
oh, thank you. 
It looks like i did something wrong, while making u-boot..
